import type { Vulnerability, Agent, TrafficEntry, TrainingModule, AgentLog, DashboardStats } from '@/types';

export const DASHBOARD_STATS: DashboardStats = {
  totalVulnerabilities: 47,
  criticalCount: 3,
  highCount: 8,
  mediumCount: 19,
  lowCount: 12,
  activeAgents: 3,
  requestsProcessed: 14827,
  uptime: '4h 23m',
};

export const VULNERABILITIES: Vulnerability[] = [
  {
    id: 'vuln-001',
    title: 'SQL Injection in Login Endpoint',
    severity: 'critical',
    category: 'Injection',
    target: 'api.target.com',
    endpoint: '/api/v2/auth/login',
    method: 'POST',
    description: 'The login endpoint is vulnerable to blind SQL injection via the username parameter. The application constructs SQL queries using string concatenation without proper parameterization.',
    evidence: "POST /api/v2/auth/login HTTP/1.1\nContent-Type: application/json\n\n{\"username\":\"admin' OR 1=1--\",\"password\":\"test\"}\n\nHTTP/1.1 200 OK\n{\"token\":\"eyJhbGciOiJIUzI1NiIs...\"}",
    remediation: 'Use parameterized queries or prepared statements. Implement input validation with strict character allowlists.',
    foundAt: '2024-01-15T14:23:00Z',
    agentName: 'IDOR Hunter',
    confirmed: true,
    cvss: 9.8,
  },
  {
    id: 'vuln-002',
    title: 'Stored XSS in User Profile Bio',
    severity: 'high',
    category: 'Cross-Site Scripting',
    target: 'app.target.com',
    endpoint: '/api/v2/users/profile',
    method: 'PUT',
    description: 'The user profile bio field does not sanitize HTML input, allowing stored XSS payloads that execute when other users view the profile.',
    evidence: 'PUT /api/v2/users/profile\n{"bio":"<img src=x onerror=alert(document.cookie)>"}\n\nPayload renders unescaped in /users/{id} page.',
    remediation: 'Implement output encoding and Content-Security-Policy headers. Sanitize all user input on both client and server.',
    foundAt: '2024-01-15T14:45:00Z',
    agentName: 'Passive Hunter',
    confirmed: true,
    cvss: 8.1,
  },
  {
    id: 'vuln-003',
    title: 'IDOR on User Account Details',
    severity: 'high',
    category: 'Broken Access Control',
    target: 'api.target.com',
    endpoint: '/api/v2/users/{id}/details',
    method: 'GET',
    description: 'Authenticated users can access any other user\'s account details by modifying the user ID in the URL. No authorization check is performed beyond authentication.',
    evidence: 'GET /api/v2/users/12345/details (own)\nGET /api/v2/users/12346/details (other user)\nBoth return 200 with full PII.',
    remediation: 'Implement proper authorization checks. Verify the authenticated user has permission to access the requested resource.',
    foundAt: '2024-01-15T15:02:00Z',
    agentName: 'IDOR Hunter',
    confirmed: true,
    cvss: 7.5,
  },
  {
    id: 'vuln-004',
    title: 'Server-Side Request Forgery via URL Import',
    severity: 'critical',
    category: 'SSRF',
    target: 'api.target.com',
    endpoint: '/api/v2/import/url',
    method: 'POST',
    description: 'The URL import feature allows users to specify arbitrary URLs. The server fetches these URLs without validation, enabling SSRF to internal services and cloud metadata endpoints.',
    evidence: 'POST /api/v2/import/url\n{"url":"http://169.254.169.254/latest/meta-data/iam/security-credentials/"}\n\nHTTP/1.1 200 OK\n{"role":"prod-web-role","AccessKeyId":"ASIA..."}',
    remediation: 'Implement URL allowlisting. Block requests to private IP ranges and cloud metadata endpoints. Use a proxy for outbound requests.',
    foundAt: '2024-01-15T15:18:00Z',
    agentName: 'SSRF Scanner',
    confirmed: true,
    cvss: 9.1,
  },
  {
    id: 'vuln-005',
    title: 'JWT Token Without Expiration',
    severity: 'medium',
    category: 'Authentication',
    target: 'api.target.com',
    endpoint: '/api/v2/auth/login',
    method: 'POST',
    description: 'JWT tokens issued by the authentication endpoint have no expiration claim (exp). Tokens remain valid indefinitely, increasing risk if compromised.',
    evidence: 'Decoded JWT payload:\n{"sub":"user123","iat":1705312800}\nNo "exp" field present.',
    remediation: 'Add short-lived expiration to all JWT tokens (15-60 minutes). Implement refresh token rotation.',
    foundAt: '2024-01-15T15:30:00Z',
    agentName: 'Passive Hunter',
    confirmed: true,
    cvss: 6.5,
  },
  {
    id: 'vuln-006',
    title: 'Rate Limiting Bypass on Password Reset',
    severity: 'medium',
    category: 'Business Logic',
    target: 'app.target.com',
    endpoint: '/api/v2/auth/reset-password',
    method: 'POST',
    description: 'The password reset endpoint rate limit can be bypassed by adding X-Forwarded-For headers with different IPs, allowing brute-force attacks on reset tokens.',
    evidence: 'Sent 1000 requests with rotating X-Forwarded-For.\nAll returned 200 OK. No rate limiting enforced.',
    remediation: 'Implement rate limiting based on account, not IP. Use exponential backoff and CAPTCHA after failed attempts.',
    foundAt: '2024-01-15T15:45:00Z',
    agentName: 'Logic Flaw Hunter',
    confirmed: true,
    cvss: 5.9,
  },
  {
    id: 'vuln-007',
    title: 'Information Disclosure via Error Messages',
    severity: 'low',
    category: 'Information Disclosure',
    target: 'api.target.com',
    endpoint: '/api/v2/search',
    method: 'GET',
    description: 'Detailed stack traces and database error messages are exposed in API error responses, revealing internal architecture details.',
    evidence: 'GET /api/v2/search?q=\'\n\nHTTP/1.1 500\n{"error":"pg_query(): ERROR: unterminated quoted string at or near...","stack":"at QueryEngine.execute (server/db/pg.js:142)"}',
    remediation: 'Implement generic error messages for production. Log detailed errors server-side only.',
    foundAt: '2024-01-15T16:00:00Z',
    agentName: 'Passive Hunter',
    confirmed: true,
    cvss: 4.3,
  },
  {
    id: 'vuln-008',
    title: 'Missing CSRF Protection on State-Changing Endpoints',
    severity: 'medium',
    category: 'CSRF',
    target: 'app.target.com',
    endpoint: '/api/v2/settings/update',
    method: 'POST',
    description: 'State-changing endpoints accept requests without CSRF tokens. Combined with cookie-based auth, this enables cross-site request forgery attacks.',
    evidence: 'No CSRF token required. Request from external origin succeeded:\n<form action="https://app.target.com/api/v2/settings/update" method="POST">',
    remediation: 'Implement CSRF tokens for all state-changing operations. Use SameSite cookie attribute.',
    foundAt: '2024-01-15T16:12:00Z',
    agentName: 'Logic Flaw Hunter',
    confirmed: true,
    cvss: 6.1,
  },
  {
    id: 'vuln-009',
    title: 'Privilege Escalation via Role Parameter',
    severity: 'critical',
    category: 'Broken Access Control',
    target: 'api.target.com',
    endpoint: '/api/v2/users/register',
    method: 'POST',
    description: 'The registration endpoint accepts a "role" parameter in the request body. By specifying "admin", a new user gains administrative privileges.',
    evidence: 'POST /api/v2/users/register\n{"email":"attacker@evil.com","password":"...", "role":"admin"}\n\nHTTP/1.1 201 Created\nUser created with admin role.',
    remediation: 'Never accept role assignments from client input. Enforce role assignment server-side with proper authorization.',
    foundAt: '2024-01-15T16:30:00Z',
    agentName: 'Auth Bypass Finder',
    confirmed: true,
    cvss: 9.8,
  },
  {
    id: 'vuln-010',
    title: 'Open Redirect in OAuth Callback',
    severity: 'medium',
    category: 'Open Redirect',
    target: 'app.target.com',
    endpoint: '/auth/callback',
    method: 'GET',
    description: 'The OAuth callback redirect_uri parameter is not properly validated, allowing redirection to arbitrary external domains for phishing attacks.',
    evidence: 'GET /auth/callback?redirect_uri=https://evil.com/capture\n\nHTTP/1.1 302\nLocation: https://evil.com/capture?token=eyJ...',
    remediation: 'Implement strict redirect URI validation against a registered allowlist.',
    foundAt: '2024-01-15T16:45:00Z',
    agentName: 'Passive Hunter',
    confirmed: true,
    cvss: 5.4,
  },
  {
    id: 'vuln-011',
    title: 'Insecure File Upload — No Content-Type Validation',
    severity: 'high',
    category: 'File Upload',
    target: 'api.target.com',
    endpoint: '/api/v2/files/upload',
    method: 'POST',
    description: 'File upload endpoint accepts any file type without server-side validation. Uploading .php or .jsp files results in server-side execution.',
    evidence: 'Uploaded shell.php with Content-Type: image/png.\nFile accessible at /uploads/shell.php and executed.',
    remediation: 'Validate file content types server-side. Store uploads outside webroot. Use random filenames.',
    foundAt: '2024-01-15T17:00:00Z',
    agentName: 'Full Recon Agent',
    confirmed: true,
    cvss: 8.6,
  },
  {
    id: 'vuln-012',
    title: 'Sensitive Data in URL Parameters',
    severity: 'low',
    category: 'Information Disclosure',
    target: 'app.target.com',
    endpoint: '/api/v2/auth/verify',
    method: 'GET',
    description: 'Authentication tokens are passed as URL query parameters, exposing them in browser history, server logs, and referrer headers.',
    evidence: 'GET /api/v2/auth/verify?token=eyJhbGciOiJIUzI1NiIs...\nToken visible in access logs and Referer header.',
    remediation: 'Transmit tokens in Authorization headers or POST body. Never include secrets in URL parameters.',
    foundAt: '2024-01-15T17:15:00Z',
    agentName: 'Passive Hunter',
    confirmed: true,
    cvss: 3.7,
  },
  {
    id: 'vuln-013',
    title: 'Mass Assignment on User Update',
    severity: 'high',
    category: 'Broken Access Control',
    target: 'api.target.com',
    endpoint: '/api/v2/users/me',
    method: 'PATCH',
    description: 'The user update endpoint binds all request parameters to the user model. Attackers can modify protected fields like verified, credits, and subscription_tier.',
    evidence: 'PATCH /api/v2/users/me\n{"subscription_tier":"enterprise","credits":999999}\n\nHTTP/1.1 200 OK — fields updated.',
    remediation: 'Implement strict allowlisting of modifiable fields. Use DTOs for input validation.',
    foundAt: '2024-01-15T17:30:00Z',
    agentName: 'Logic Flaw Hunter',
    confirmed: true,
    cvss: 7.2,
  },
  {
    id: 'vuln-014',
    title: 'GraphQL Introspection Enabled in Production',
    severity: 'low',
    category: 'Information Disclosure',
    target: 'api.target.com',
    endpoint: '/graphql',
    method: 'POST',
    description: 'GraphQL introspection is enabled, exposing the entire API schema including internal types, mutations, and deprecated fields.',
    evidence: 'POST /graphql\n{"query":"{__schema{types{name fields{name}}}}"}\n\nFull schema returned with 142 types.',
    remediation: 'Disable introspection in production. Implement query complexity limits and field-level authorization.',
    foundAt: '2024-01-15T17:45:00Z',
    agentName: 'Full Recon Agent',
    confirmed: true,
    cvss: 4.0,
  },
  {
    id: 'vuln-015',
    title: 'Weak Password Policy — No Complexity Requirements',
    severity: 'medium',
    category: 'Authentication',
    target: 'app.target.com',
    endpoint: '/api/v2/users/register',
    method: 'POST',
    description: 'The registration endpoint accepts passwords as short as 1 character with no complexity requirements. Common passwords like "password" are accepted.',
    evidence: 'POST /api/v2/users/register\n{"email":"test@test.com","password":"1"}\n\nHTTP/1.1 201 Created',
    remediation: 'Enforce minimum 12 character passwords. Check against breached password databases. Require complexity.',
    foundAt: '2024-01-15T18:00:00Z',
    agentName: 'Auth Bypass Finder',
    confirmed: true,
    cvss: 5.3,
  },
  {
    id: 'vuln-016',
    title: 'CORS Misconfiguration — Wildcard with Credentials',
    severity: 'high',
    category: 'Misconfiguration',
    target: 'api.target.com',
    endpoint: '/*',
    method: 'GET',
    description: 'The API reflects the Origin header in Access-Control-Allow-Origin with credentials allowed, enabling any domain to make authenticated cross-origin requests.',
    evidence: 'Origin: https://evil.com\n\nAccess-Control-Allow-Origin: https://evil.com\nAccess-Control-Allow-Credentials: true',
    remediation: 'Implement strict origin allowlisting. Never reflect arbitrary origins with credentials enabled.',
    foundAt: '2024-01-15T18:15:00Z',
    agentName: 'Passive Hunter',
    confirmed: true,
    cvss: 7.4,
  },
  {
    id: 'vuln-017',
    title: 'NoSQL Injection in Search Filter',
    severity: 'high',
    category: 'Injection',
    target: 'api.target.com',
    endpoint: '/api/v2/products/search',
    method: 'POST',
    description: 'The search filter accepts MongoDB query operators, allowing NoSQL injection that can bypass authentication or extract data.',
    evidence: 'POST /api/v2/products/search\n{"price":{"$gt":0},"$where":"sleep(5000)"}\n\nResponse delayed by 5 seconds.',
    remediation: 'Sanitize all input against NoSQL operators. Use parameterized queries with MongoDB driver.',
    foundAt: '2024-01-15T18:30:00Z',
    agentName: 'API Fuzzer',
    confirmed: true,
    cvss: 8.2,
  },
  {
    id: 'vuln-018',
    title: 'Path Traversal in File Download',
    severity: 'high',
    category: 'Path Traversal',
    target: 'api.target.com',
    endpoint: '/api/v2/files/download',
    method: 'GET',
    description: 'The file download endpoint is vulnerable to path traversal. Attackers can read arbitrary server files by manipulating the filename parameter.',
    evidence: 'GET /api/v2/files/download?file=../../../etc/passwd\n\nHTTP/1.1 200 OK\nroot:x:0:0:root:/root:/bin/bash...',
    remediation: 'Validate and sanitize file paths. Use an allowlist of permitted directories. Resolve canonical paths before serving.',
    foundAt: '2024-01-15T18:45:00Z',
    agentName: 'Full Recon Agent',
    confirmed: true,
    cvss: 7.8,
  },
  {
    id: 'vuln-019',
    title: 'Clickjacking — Missing X-Frame-Options',
    severity: 'low',
    category: 'Misconfiguration',
    target: 'app.target.com',
    endpoint: '/*',
    method: 'GET',
    description: 'The application does not set X-Frame-Options or frame-ancestors CSP directive, allowing the site to be embedded in iframes for clickjacking attacks.',
    evidence: 'No X-Frame-Options header.\nNo Content-Security-Policy frame-ancestors.\nSuccessfully framed the login page.',
    remediation: 'Set X-Frame-Options: DENY and Content-Security-Policy: frame-ancestors \'none\'.',
    foundAt: '2024-01-15T19:00:00Z',
    agentName: 'Passive Hunter',
    confirmed: true,
    cvss: 4.7,
  },
  {
    id: 'vuln-020',
    title: 'Session Fixation via URL Token',
    severity: 'medium',
    category: 'Session Management',
    target: 'app.target.com',
    endpoint: '/auth/sso',
    method: 'GET',
    description: 'The SSO login flow accepts a session token from the URL and does not regenerate it after authentication, enabling session fixation attacks.',
    evidence: 'GET /auth/sso?session=attacker-controlled-token\nAfter login, same session token is used for authenticated session.',
    remediation: 'Always regenerate session identifiers after authentication. Never accept session tokens from URL parameters.',
    foundAt: '2024-01-15T19:15:00Z',
    agentName: 'Auth Bypass Finder',
    confirmed: true,
    cvss: 6.3,
  },
];

export const AGENTS: Agent[] = [
  {
    id: 'agent-001',
    name: 'Passive Recon Alpha',
    type: 'passive_hunter',
    description: 'Analyzing proxy history for information disclosure, misconfigurations, and sensitive data exposure.',
    status: 'running',
    target: '*.target.com',
    progress: 67,
    findings: 12,
    requestsSent: 0,
    startedAt: '2024-01-15T14:00:00Z',
    lastAction: 'Analyzing response headers for security misconfigurations',
    promptTemplate: 'passive_hunter',
    safetyMode: 'passive',
  },
  {
    id: 'agent-002',
    name: 'IDOR Strike Team',
    type: 'idor_hunter',
    description: 'Testing authorization boundaries across user-specific endpoints by substituting identifiers.',
    status: 'running',
    target: 'api.target.com',
    progress: 43,
    findings: 5,
    requestsSent: 342,
    startedAt: '2024-01-15T14:30:00Z',
    lastAction: 'Testing /api/v2/orders/{id} with cross-user token',
    promptTemplate: 'idor_hunter',
    safetyMode: 'cautious',
  },
  {
    id: 'agent-003',
    name: 'Logic Flaw Seeker',
    type: 'logic_flaw_hunter',
    description: 'Probing business logic for race conditions, workflow bypasses, and privilege escalation paths.',
    status: 'running',
    target: 'app.target.com',
    progress: 28,
    findings: 3,
    requestsSent: 156,
    startedAt: '2024-01-15T15:00:00Z',
    lastAction: 'Testing concurrent checkout flow for race conditions',
    promptTemplate: 'logic_flaw_hunter',
    safetyMode: 'cautious',
  },
  {
    id: 'agent-004',
    name: 'SSRF Probe Delta',
    type: 'ssrf_scanner',
    description: 'Testing all URL-accepting parameters for server-side request forgery to internal services.',
    status: 'paused',
    target: 'api.target.com',
    progress: 89,
    findings: 2,
    requestsSent: 87,
    startedAt: '2024-01-15T13:00:00Z',
    lastAction: 'Paused — awaiting confirmation for internal network scan',
    promptTemplate: 'ssrf_scanner',
    safetyMode: 'cautious',
  },
  {
    id: 'agent-005',
    name: 'Auth Bypass Epsilon',
    type: 'auth_bypass',
    description: 'Attempting authentication bypass via token manipulation, header injection, and session handling flaws.',
    status: 'completed',
    target: '*.target.com',
    progress: 100,
    findings: 4,
    requestsSent: 523,
    startedAt: '2024-01-15T10:00:00Z',
    lastAction: 'Scan complete — 4 findings generated',
    promptTemplate: 'auth_bypass',
    safetyMode: 'aggressive',
  },
  {
    id: 'agent-006',
    name: 'API Fuzz Zeta',
    type: 'api_fuzzer',
    description: 'Discovering hidden API endpoints and fuzzing parameters with intelligent mutation strategies.',
    status: 'idle',
    target: 'api.target.com',
    progress: 0,
    findings: 0,
    requestsSent: 0,
    startedAt: null,
    lastAction: 'Ready to deploy',
    promptTemplate: 'api_fuzzer',
    safetyMode: 'cautious',
  },
];

export const TRAFFIC_ENTRIES: TrafficEntry[] = [
  { id: 't-001', timestamp: '19:15:42', method: 'GET', url: '/api/v2/users/me', statusCode: 200, responseTime: 45, size: 1240, source: 'Browser', flagged: false },
  { id: 't-002', timestamp: '19:15:43', method: 'POST', url: '/api/v2/auth/login', statusCode: 200, responseTime: 320, size: 456, source: 'IDOR Hunter', flagged: true },
  { id: 't-003', timestamp: '19:15:44', method: 'GET', url: '/api/v2/products?page=1', statusCode: 200, responseTime: 89, size: 8923, source: 'Browser', flagged: false },
  { id: 't-004', timestamp: '19:15:45', method: 'PUT', url: '/api/v2/users/profile', statusCode: 200, responseTime: 156, size: 234, source: 'Logic Flaw', flagged: true },
  { id: 't-005', timestamp: '19:15:46', method: 'GET', url: '/api/v2/orders/12345', statusCode: 200, responseTime: 67, size: 2341, source: 'IDOR Hunter', flagged: true },
  { id: 't-006', timestamp: '19:15:47', method: 'DELETE', url: '/api/v2/sessions/old', statusCode: 204, responseTime: 23, size: 0, source: 'Browser', flagged: false },
  { id: 't-007', timestamp: '19:15:48', method: 'POST', url: '/api/v2/import/url', statusCode: 200, responseTime: 2340, size: 5678, source: 'SSRF Probe', flagged: true },
  { id: 't-008', timestamp: '19:15:49', method: 'GET', url: '/api/v2/files/download?file=report.pdf', statusCode: 200, responseTime: 445, size: 45678, source: 'Browser', flagged: false },
  { id: 't-009', timestamp: '19:15:50', method: 'PATCH', url: '/api/v2/users/me', statusCode: 200, responseTime: 78, size: 456, source: 'Logic Flaw', flagged: true },
  { id: 't-010', timestamp: '19:15:51', method: 'GET', url: '/api/v2/admin/users', statusCode: 403, responseTime: 12, size: 89, source: 'Auth Bypass', flagged: true },
  { id: 't-011', timestamp: '19:15:52', method: 'POST', url: '/graphql', statusCode: 200, responseTime: 234, size: 12345, source: 'Full Recon', flagged: true },
  { id: 't-012', timestamp: '19:15:53', method: 'GET', url: '/robots.txt', statusCode: 200, responseTime: 5, size: 234, source: 'Full Recon', flagged: false },
  { id: 't-013', timestamp: '19:15:54', method: 'POST', url: '/api/v2/products/search', statusCode: 500, responseTime: 5023, size: 1234, source: 'API Fuzzer', flagged: true },
  { id: 't-014', timestamp: '19:15:55', method: 'GET', url: '/api/v2/health', statusCode: 200, responseTime: 8, size: 45, source: 'Browser', flagged: false },
  { id: 't-015', timestamp: '19:15:56', method: 'GET', url: '/api/v2/users/12346/details', statusCode: 200, responseTime: 56, size: 2345, source: 'IDOR Hunter', flagged: true },
  { id: 't-016', timestamp: '19:15:57', method: 'POST', url: '/api/v2/auth/reset-password', statusCode: 200, responseTime: 89, size: 123, source: 'Logic Flaw', flagged: true },
  { id: 't-017', timestamp: '19:15:58', method: 'GET', url: '/api/v2/config', statusCode: 200, responseTime: 34, size: 567, source: 'Full Recon', flagged: true },
  { id: 't-018', timestamp: '19:15:59', method: 'OPTIONS', url: '/api/v2/users/me', statusCode: 200, responseTime: 3, size: 0, source: 'Browser', flagged: false },
  { id: 't-019', timestamp: '19:16:00', method: 'GET', url: '/api/v2/users/register', statusCode: 405, responseTime: 12, size: 89, source: 'Auth Bypass', flagged: false },
  { id: 't-020', timestamp: '19:16:01', method: 'POST', url: '/api/v2/files/upload', statusCode: 200, responseTime: 1234, size: 234, source: 'Full Recon', flagged: true },
];

export const TRAINING_MODULES: TrainingModule[] = [
  {
    id: 'tm-001',
    title: 'Burp Suite Fundamentals',
    description: 'Master the core tools: Proxy, Target, Repeater. Learn to intercept, inspect, and modify HTTP traffic.',
    category: 'Fundamentals',
    difficulty: 'beginner',
    lessons: 8,
    completedLessons: 8,
    duration: '2h 30m',
    topics: ['Proxy Setup', 'Intercepting Traffic', 'Target Scope', 'Repeater Basics', 'HTTP History'],
    locked: false,
  },
  {
    id: 'tm-002',
    title: 'Intruder Attacks Deep Dive',
    description: 'Learn all Intruder attack types: Sniper, Battering Ram, Pitchfork, Cluster Bomb. Build custom payload lists.',
    category: 'Core Tools',
    difficulty: 'intermediate',
    lessons: 6,
    completedLessons: 4,
    duration: '1h 45m',
    topics: ['Attack Types', 'Payload Processing', 'Grep Match Rules', 'Resource Pools', 'Payload Generators'],
    locked: false,
  },
  {
    id: 'tm-003',
    title: 'Scanner & Active Testing',
    description: 'Configure and optimize the Burp Scanner. Understand scan types, crawling strategies, and audit configurations.',
    category: 'Core Tools',
    difficulty: 'intermediate',
    lessons: 5,
    completedLessons: 2,
    duration: '1h 30m',
    topics: ['Passive Scanning', 'Active Scanning', 'Crawl Config', 'Audit Config', 'Scan Results Analysis'],
    locked: false,
  },
  {
    id: 'tm-004',
    title: 'Extensions & BApp Store',
    description: 'Install and configure essential extensions. Write your first custom extension using the Montoya API.',
    category: 'Advanced',
    difficulty: 'advanced',
    lessons: 7,
    completedLessons: 0,
    duration: '2h 15m',
    topics: ['BApp Store', 'Extension Types', 'Montoya API', 'Custom Checks', 'Extension Debugging'],
    locked: false,
  },
  {
    id: 'tm-005',
    title: 'Session Handling & Macros',
    description: 'Build complex session handling rules and macros for testing authenticated and multi-step workflows.',
    category: 'Advanced',
    difficulty: 'advanced',
    lessons: 5,
    completedLessons: 0,
    duration: '1h 45m',
    topics: ['Session Rules', 'Macro Recording', 'Cookie Jar', 'Token Extraction', 'Rule Chains'],
    locked: false,
  },
  {
    id: 'tm-006',
    title: 'MCP Integration Mastery',
    description: 'Connect AI agents to Burp Suite via MCP. Build autonomous testing workflows with intelligent tool use.',
    category: 'MCP & AI',
    difficulty: 'advanced',
    lessons: 6,
    completedLessons: 0,
    duration: '2h 00m',
    topics: ['MCP Server Setup', 'Tool Registration', 'AI Agent Connection', 'Autonomous Workflows', 'Safety Controls'],
    locked: false,
  },
  {
    id: 'tm-007',
    title: 'Custom Scan Checks & Audit Items',
    description: 'Write custom passive and active scan checks. Create specialized vulnerability detection for business logic.',
    category: 'Expert',
    difficulty: 'expert',
    lessons: 8,
    completedLessons: 0,
    duration: '3h 00m',
    topics: ['IScannerCheck', 'Passive Checks', 'Active Checks', 'Issue Reporting', 'Insertion Points'],
    locked: true,
  },
  {
    id: 'tm-008',
    title: 'Advanced Agent Orchestration',
    description: 'Build multi-agent systems that coordinate attacks. Chain agents for complex vulnerability discovery chains.',
    category: 'MCP & AI',
    difficulty: 'expert',
    lessons: 6,
    completedLessons: 0,
    duration: '2h 30m',
    topics: ['Multi-Agent Systems', 'Agent Communication', 'Attack Chains', 'Coordinated Scanning', 'Report Synthesis'],
    locked: true,
  },
];

export const AGENT_LOGS: AgentLog[] = [
  { id: 'log-001', agentId: 'agent-002', timestamp: '19:15:42', type: 'thought', content: 'Observed 23 endpoints with user-specific IDs in proxy history. Starting horizontal privilege testing on /api/v2/users/{id}/details endpoint.' },
  { id: 'log-002', agentId: 'agent-002', timestamp: '19:15:43', type: 'action', content: 'SEND_REQUEST: GET /api/v2/users/12346/details with User A token (expected: 403, testing cross-user access)' },
  { id: 'log-003', agentId: 'agent-002', timestamp: '19:15:44', type: 'observation', content: 'Response: 200 OK with full user PII for user 12346. Authorization check missing — horizontal privilege escalation confirmed.' },
  { id: 'log-004', agentId: 'agent-002', timestamp: '19:15:44', type: 'finding', content: '🔴 IDOR CONFIRMED on /api/v2/users/{id}/details — any authenticated user can access other users\' personal data. CVSS: 7.5 (High)' },
  { id: 'log-005', agentId: 'agent-002', timestamp: '19:15:45', type: 'thought', content: 'Checking if the same pattern exists on /api/v2/users/{id}/orders and /api/v2/users/{id}/payments endpoints.' },
  { id: 'log-006', agentId: 'agent-002', timestamp: '19:15:46', type: 'action', content: 'SEND_REQUEST: GET /api/v2/users/12346/orders with User A token' },
  { id: 'log-007', agentId: 'agent-002', timestamp: '19:15:47', type: 'observation', content: 'Response: 200 OK — order history for user 12346 returned. Same IDOR pattern confirmed across order endpoints.' },
  { id: 'log-008', agentId: 'agent-003', timestamp: '19:15:48', type: 'thought', content: 'Testing race condition on /api/v2/checkout — sending 10 concurrent requests to apply discount code multiple times.' },
  { id: 'log-009', agentId: 'agent-003', timestamp: '19:15:49', type: 'action', content: 'SEND_CONCURRENT: 10x POST /api/v2/checkout/apply-discount with code=SUMMER50' },
  { id: 'log-010', agentId: 'agent-003', timestamp: '19:15:50', type: 'observation', content: '7 out of 10 requests succeeded. Discount applied 7 times — original $100 item priced at -$250. Race condition in discount application logic.' },
  { id: 'log-011', agentId: 'agent-003', timestamp: '19:15:50', type: 'finding', content: '🟠 RACE CONDITION in discount application — concurrent requests bypass single-use check. Negative pricing achieved.' },
  { id: 'log-012', agentId: 'agent-001', timestamp: '19:15:51', type: 'thought', content: 'Scanning response headers across all captured traffic. Looking for missing security headers and information leakage.' },
  { id: 'log-013', agentId: 'agent-001', timestamp: '19:15:52', type: 'observation', content: 'Found 45 responses missing X-Frame-Options. 12 responses include Server header revealing "nginx/1.21.3". All /api/* responses missing Content-Security-Policy.' },
  { id: 'log-014', agentId: 'agent-001', timestamp: '19:15:53', type: 'action', content: 'ANALYZE: Checking Set-Cookie attributes across all authentication responses.' },
  { id: 'log-015', agentId: 'agent-001', timestamp: '19:15:54', type: 'observation', content: 'Session cookies missing Secure and HttpOnly flags on 3 endpoints. SameSite attribute not set.' },
  { id: 'log-016', agentId: 'agent-001', timestamp: '19:15:55', type: 'finding', content: '🟡 SECURITY HEADER GAPS — Missing X-Frame-Options (45), CSP (all API), insecure cookie attributes (3 auth endpoints). Server version disclosure.' },
  { id: 'log-017', agentId: 'agent-002', timestamp: '19:15:56', type: 'thought', content: 'Moving to vertical privilege testing. Attempting to access admin endpoints with regular user token.' },
  { id: 'log-018', agentId: 'agent-002', timestamp: '19:15:57', type: 'action', content: 'SEND_REQUEST: GET /api/v2/admin/users with regular user Bearer token' },
  { id: 'log-019', agentId: 'agent-002', timestamp: '19:15:58', type: 'observation', content: 'Response: 403 Forbidden — admin endpoint properly protected. Moving to test admin-like functionality on non-admin routes.' },
  { id: 'log-020', agentId: 'agent-002', timestamp: '19:15:59', type: 'thought', content: 'Testing if PATCH /api/v2/users/me accepts role or admin fields for mass assignment privilege escalation.' },
];

export const VULNERABILITY_CHART_DATA = [
  { name: 'Mon', critical: 0, high: 2, medium: 3, low: 1 },
  { name: 'Tue', critical: 1, high: 1, medium: 5, low: 2 },
  { name: 'Wed', critical: 0, high: 3, medium: 4, low: 3 },
  { name: 'Thu', critical: 1, high: 2, medium: 2, low: 2 },
  { name: 'Fri', critical: 0, high: 0, medium: 3, low: 1 },
  { name: 'Sat', critical: 1, high: 0, medium: 2, low: 3 },
  { name: 'Now', critical: 3, high: 8, medium: 19, low: 12 },
];

export const REQUEST_RATE_DATA = [
  { time: '14:00', rate: 12 },
  { time: '14:15', rate: 45 },
  { time: '14:30', rate: 78 },
  { time: '14:45', rate: 120 },
  { time: '15:00', rate: 95 },
  { time: '15:15', rate: 156 },
  { time: '15:30', rate: 210 },
  { time: '15:45', rate: 180 },
  { time: '16:00', rate: 245 },
  { time: '16:15', rate: 190 },
  { time: '16:30', rate: 278 },
  { time: '16:45', rate: 320 },
  { time: '17:00', rate: 290 },
  { time: '17:15', rate: 256 },
  { time: '17:30', rate: 310 },
  { time: '17:45', rate: 345 },
  { time: '18:00', rate: 280 },
  { time: '18:15', rate: 230 },
  { time: '18:30', rate: 198 },
  { time: '18:45', rate: 267 },
  { time: '19:00', rate: 312 },
  { time: '19:15', rate: 289 },
];
